"""empty message

Revision ID: e7ced229acda
Revises: ed049378f5b3
Create Date: 2023-07-07 14:27:27.462276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7ced229acda'
down_revision = 'ed049378f5b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bookname', sa.String(), nullable=True),
    sa.Column('shelf', sa.String(), nullable=True),
    sa.Column('block', sa.String(), nullable=True),
    sa.Column('writer', sa.String(), nullable=True),
    sa.Column('loan', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_books_block'), ['block'], unique=False)
        batch_op.create_index(batch_op.f('ix_books_bookname'), ['bookname'], unique=False)
        batch_op.create_index(batch_op.f('ix_books_loan'), ['loan'], unique=False)
        batch_op.create_index(batch_op.f('ix_books_shelf'), ['shelf'], unique=False)
        batch_op.create_index(batch_op.f('ix_books_writer'), ['writer'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_books_writer'))
        batch_op.drop_index(batch_op.f('ix_books_shelf'))
        batch_op.drop_index(batch_op.f('ix_books_loan'))
        batch_op.drop_index(batch_op.f('ix_books_bookname'))
        batch_op.drop_index(batch_op.f('ix_books_block'))

    op.drop_table('books')
    # ### end Alembic commands ###
