"""empty message

Revision ID: ed049378f5b3
Revises: 32e77e6b59de
Create Date: 2023-07-05 23:25:43.241073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed049378f5b3'
down_revision = '32e77e6b59de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_student_id')
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.VARCHAR(), nullable=True))
        batch_op.create_index('ix_users_student_id', ['student_id'], unique=False)

    # ### end Alembic commands ###
